import { AuthorizedAppRecord } from "@/features/authorized-apps/types"

export const MOCK_AUTHORIZED_APPS: AuthorizedAppRecord[] = [
  {
    _id: "1",
    name: "TaskFlow Pro",
    url: "https://taskflow-pro.example.com",
    lastAccessedAt: "2024-02-01T12:00:00Z",
    insertedAt: "2023-11-15T09:23:14Z",
    scopes: [
      { id: "calendar_read", type: "data", description: "Read calendar data" },
      { id: "event_write", type: "data", description: "Write social events" },
      { id: "chat_read", type: "data", description: "Read chat messages" },
    ],
  },
  {
    _id: "2",
    name: "ConnectMail Plus",
    url: "https://connectmail.example.com",
    lastAccessedAt: "2024-02-10T15:30:00Z",
    insertedAt: "2023-12-01T14:45:22Z",
    scopes: [
      { id: "email_read", type: "data", description: "Read emails" },
      { id: "contact_read", type: "data", description: "Read contacts" },
    ],
  },
  {
    _id: "3",
    name: "SecureVault Manager",
    url: "https://securevault.example.com",
    lastAccessedAt: "2024-02-12T09:15:00Z",
    insertedAt: "2023-10-28T11:12:33Z",
    scopes: [
      {
        id: "credential_write",
        type: "data",
        description: "Write credentials",
      },
      { id: "contact_read", type: "data", description: "Read contacts" },
      { id: "file_read", type: "data", description: "Read files" },
    ],
  },
  {
    _id: "4",
    name: "TeamChat Hub",
    url: "https://teamchat.example.com",
    lastAccessedAt: "2024-02-13T18:45:00Z",
    insertedAt: "2023-09-15T16:34:51Z",
    scopes: [
      { id: "chat_write", type: "data", description: "Write chat messages" },
      { id: "group_read", type: "data", description: "Read chat groups" },
      { id: "contact_read", type: "data", description: "Read contacts" },
    ],
  },
  {
    _id: "5",
    name: "Web3 Identity Bridge",
    url: "https://identity-bridge.example.com",
    lastAccessedAt: "2024-02-14T11:20:00Z",
    insertedAt: "2024-01-02T08:17:44Z",
    scopes: [
      { id: "contact_read", type: "data", description: "Read contacts" },
      { id: "credential_read", type: "data", description: "Read credentials" },
      {
        id: "following_read",
        type: "data",
        description: "Read following data",
      },
      { id: "favourite_read", type: "data", description: "Read favorites" },
      { id: "file_read", type: "data", description: "Read files" },
    ],
  },
  {
    _id: "6",
    name: "SocialSphere Connect",
    url: "https://socialsphere.example.com",
    lastAccessedAt: "2024-02-15T14:10:00Z",
    insertedAt: "2023-11-30T13:56:19Z",
    scopes: [
      { id: "post_write", type: "data", description: "Write social posts" },
      {
        id: "following_read",
        type: "data",
        description: "Read following data",
      },
    ],
  },
  {
    _id: "7",
    name: "EventSync Pro",
    url: "https://eventsync.example.com",
    lastAccessedAt: "2024-02-16T16:25:00Z",
    insertedAt: "2023-12-12T15:23:41Z",
    scopes: [
      { id: "event_write", type: "data", description: "Write social events" },
      { id: "calendar_read", type: "data", description: "Read calendar data" },
      { id: "group_read", type: "data", description: "Read chat groups" },
      { id: "contact_read", type: "data", description: "Read contacts" },
    ],
  },
  {
    _id: "8",
    name: "CloudStore Sync",
    url: "https://cloudstore.example.com",
    lastAccessedAt: "2024-02-17T08:50:00Z",
    insertedAt: "2023-10-05T09:44:12Z",
    scopes: [{ id: "file_write", type: "data", description: "Write files" }],
  },
  {
    _id: "9",
    name: "DeFi Portfolio Tracker",
    url: "https://defi-tracker.example.com",
    lastAccessedAt: "2024-02-18T13:40:00Z",
    insertedAt: "2023-12-28T17:11:33Z",
    scopes: [
      { id: "credential_read", type: "data", description: "Read credentials" },
      { id: "favourite_write", type: "data", description: "Write favorites" },
      {
        id: "following_read",
        type: "data",
        description: "Read following data",
      },
      { id: "contact_read", type: "data", description: "Read contacts" },
      { id: "file_read", type: "data", description: "Read files" },
      { id: "post_read", type: "data", description: "Read social posts" },
    ],
  },
  {
    _id: "10",
    name: "ContentHub Studio",
    url: "https://contenthub.example.com",
    lastAccessedAt: "2024-02-19T20:15:00Z",
    insertedAt: "2024-01-10T12:09:55Z",
    scopes: [
      { id: "post_write", type: "data", description: "Write social posts" },
    ],
  },
  {
    _id: "11",
    name: "NFT Collection Manager",
    url: "https://nft-manager.example.com",
    lastAccessedAt: "2024-02-20T10:30:00Z",
    insertedAt: "2023-11-22T10:33:27Z",
    scopes: [
      { id: "file_read", type: "data", description: "Read files" },
      { id: "post_write", type: "data", description: "Write social posts" },
      { id: "credential_read", type: "data", description: "Read credentials" },
    ],
  },
  {
    _id: "12",
    name: "WorkFlow Organizer",
    url: "https://workflow.example.com",
    lastAccessedAt: "2024-02-21T17:05:00Z",
    insertedAt: "2023-12-15T14:22:48Z",
    scopes: [
      { id: "event_write", type: "data", description: "Write social events" },
      { id: "group_read", type: "data", description: "Read chat groups" },
      { id: "calendar_read", type: "data", description: "Read calendar data" },
      { id: "contact_read", type: "data", description: "Read contacts" },
    ],
  },
]
