name: CI

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Check, Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODE_VERSION }}"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn run check:format

      - name: Check linting
        run: yarn run check:lint

      - name: Check TypeScript compilation
        run: yarn run check:ts

      # TODO: Add tests in CI when available
      #
      # TODO: Add build in CI. Building needs the env vars to be set.
      # - name: Build
      #   run: yarn run build --no-lint
